import type { Tournament } from '../challongeApi'

const tournament: Tournament = {
    id: 15888901,
    name: 'test',
    url: 'xq6estdx',
    description: 'Created by the Draft Bot 🤖',
    tournament_type: 'round robin',
    started_at: '2025-03-04T23:06:23.044-08:00',
    completed_at: '2025-03-04T23:07:26.790-08:00',
    require_score_agreement: false,
    notify_users_when_matches_open: true,
    created_at: '2025-03-04T23:05:52.704-08:00',
    updated_at: '2025-03-04T23:07:26.845-08:00',
    state: 'complete',
    open_signup: true,
    notify_users_when_the_tournament_ends: true,
    progress_meter: 100,
    quick_advance: false,
    hold_third_place_match: false,
    pts_for_game_win: '0.0',
    pts_for_game_tie: '0.0',
    pts_for_match_win: '1.0',
    pts_for_match_tie: '0.5',
    pts_for_bye: '1.0',
    swiss_rounds: 1,
    private: false,
    ranked_by: 'match wins',
    show_rounds: false,
    hide_forum: false,
    sequential_pairings: false,
    accept_attachments: false,
    rr_pts_for_game_win: '0.0',
    rr_pts_for_game_tie: '0.0',
    rr_pts_for_match_win: '1.0',
    rr_pts_for_match_tie: '0.5',
    created_by_api: true,
    credit_capped: false,
    category: null,
    hide_seeds: false,
    prediction_method: 0,
    predictions_opened_at: null,
    anonymous_voting: false,
    max_predictions_per_user: 1,
    signup_cap: null,
    game_id: 289,
    participants_count: 2,
    group_stages_enabled: false,
    allow_participant_match_reporting: true,
    teams: null,
    check_in_duration: null,
    start_at: null,
    started_checking_in_at: null,
    tie_breaks: null,
    locked_at: null,
    event_id: null,
    public_predictions_before_start_time: null,
    ranked: null,
    grand_finals_modifier: null,
    predict_the_losers_bracket: null,
    spam: null,
    ham: null,
    rr_iterations: null,
    tournament_registration_id: null,
    donation_contest_enabled: null,
    mandatory_donation: null,
    non_elimination_tournament_data: {},
    auto_assign_stations: null,
    only_start_matches_with_stations: null,
    registration_fee: '0.0',
    registration_type: 'free',
    split_participants: false,
    allowed_regions: null,
    show_participant_country: null,
    program_id: null,
    program_classification_ids_allowed: null,
    team_size_range: null,
    toxic: null,
    use_new_style: null,
    optional_display_data: { show_standings: '1', show_announcements: true },
    processing: false,
    oauth_application_id: null,
    hide_bracket_preview: null,
    consolation_matches_target_rank: null,
    review_swiss_pairings_before_starting_rounds: null,
    allow_incomplete_rosters: null,
    check_in_onsite: null,
    participants: [
        {
            participant: {
                id: 256201442,
                tournament_id: 15888901,
                name: 'reptarsrage',
                seed: 1,
                active: true,
                created_at: '2025-03-04T23:06:00.754-08:00',
                updated_at: '2025-03-04T23:06:00.754-08:00',
                invite_email: null,
                final_rank: 1,
                misc: null,
                icon: null,
                on_waiting_list: false,
                invitation_id: null,
                group_id: null,
                checked_in_at: null,
                ranked_member_id: null,
                custom_field_response: null,
                clinch: null,
                integration_uids: null,
                challonge_username: null,
                challonge_user_id: null,
                challonge_email_address_verified: null,
                removable: false,
                participatable_or_invitation_attached: false,
                confirm_remove: true,
                invitation_pending: false,
                display_name_with_invitation_email_address: 'reptarsrage',
                email_hash: null,
                username: null,
                display_name: 'reptarsrage',
                attached_participatable_portrait_url: null,
                can_check_in: false,
                checked_in: false,
                reactivatable: false,
                check_in_open: false,
                group_player_ids: [],
                has_irrelevant_seed: false,
                ordinal_seed: '1st',
                roster_complete: null,
                roster_size: null,
            },
        },
        {
            participant: {
                id: 256201447,
                tournament_id: 15888901,
                name: 'poop',
                seed: 2,
                active: true,
                created_at: '2025-03-04T23:06:18.231-08:00',
                updated_at: '2025-03-04T23:06:18.231-08:00',
                invite_email: null,
                final_rank: 2,
                misc: null,
                icon: null,
                on_waiting_list: false,
                invitation_id: null,
                group_id: null,
                checked_in_at: null,
                ranked_member_id: null,
                custom_field_response: null,
                clinch: null,
                integration_uids: null,
                challonge_username: null,
                challonge_user_id: null,
                challonge_email_address_verified: null,
                removable: false,
                participatable_or_invitation_attached: false,
                confirm_remove: true,
                invitation_pending: false,
                display_name_with_invitation_email_address: 'poop',
                email_hash: null,
                username: null,
                display_name: 'poop',
                attached_participatable_portrait_url: null,
                can_check_in: false,
                checked_in: false,
                reactivatable: false,
                check_in_open: false,
                group_player_ids: [],
                has_irrelevant_seed: false,
                ordinal_seed: '2nd',
                roster_complete: null,
                roster_size: null,
            },
        },
    ],
    matches: [
        {
            match: {
                id: 403648690,
                tournament_id: 15888901,
                state: 'complete',
                player1_id: 256201447,
                player2_id: 256201442,
                player1_prereq_match_id: null,
                player2_prereq_match_id: null,
                player1_is_prereq_match_loser: false,
                player2_is_prereq_match_loser: false,
                winner_id: 256201442,
                loser_id: 256201447,
                started_at: '2025-03-04T23:06:23.154-08:00',
                created_at: '2025-03-04T23:06:23.038-08:00',
                updated_at: '2025-03-04T23:07:08.484-08:00',
                identifier: 'A',
                has_attachment: false,
                round: 1,
                player1_votes: null,
                player2_votes: null,
                group_id: null,
                attachment_count: null,
                scheduled_time: null,
                location: null,
                underway_at: null,
                optional: null,
                completed_at: '2025-03-04T23:07:08.488-08:00',
                suggested_play_order: 1,
                forfeited: null,
                open_graph_image_file_name: null,
                open_graph_image_content_type: null,
                open_graph_image_file_size: null,
                prerequisite_match_ids_csv: '',
                scores_csv: '2-1',
            },
        },
    ],
    description_source: 'Created by the Draft Bot 🤖',
    subdomain: null,
    full_challonge_url: 'https://challonge.com/xq6estdx',
    live_image_url: 'https://challonge.com/xq6estdx.svg',
    sign_up_url: 'https://challonge.com/tournaments/signup/Ckmi5yI6rN',
    review_before_finalizing: true,
    accepting_predictions: false,
    participants_locked: true,
    game_name: 'Magic: The Gathering',
    participants_swappable: false,
    team_convertable: false,
    group_stages_were_started: false,
}

export default tournament
